"""initial

Revision ID: 64726d6e26a8
Revises: 
Create Date: 2026-06-17 01:36:31.707266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '64726d6e26a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('our_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('trigger_event', sa.JSON(), nullable=True),
    sa.Column('price_comparison', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.String(length=64), nullable=True),
    sa.Column('proposed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_margin', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('strategic_narrative', sa.Text(), nullable=True),
    sa.Column('llm_recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('competitor_name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentiment_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_payload', sa.JSON(), nullable=False),
    sa.Column('draft_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('competitor_id', sa.String(length=36), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_snapshots')
    op.drop_table('pending_actions')
    op.drop_table('sentiment_records')
    op.drop_table('competitors')
    op.drop_table('analysis_reports')
    op.drop_table('products')
    # ### end Alembic commands ###
